# Generated by Django 5.2.2 on 2025-06-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfectSpot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, to='PerfectSpot.interest'),
        ),
    ]
