# Generated by Django 4.2.20 on 2025-03-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfectSpot', '0002_organizationproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Individual User',
                'verbose_name_plural': 'Individual Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('PerfectSpot.customuser',),
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_org_verified',
            field=models.BooleanField(default=False, help_text='Admin-approved verification of organization documents'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
