# Generated by Django 4.2.20 on 2025-06-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfectSpot', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
