# Generated by Django 4.2.20 on 2025-06-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfectSpot', '0004_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preview_url',
            field=models.CharField(blank=True, help_text='URL of the event’s preview image or page', max_length=255, null=True),
        ),
    ]
